#!/bin/bash
# Database conf info

deps="mysql"
for p in $deps; do
	command -v $p > /dev/null || {
		echo "This script need \"$p\""
	exit 1
	}
done


# DB info
DB_HOST=127.0.0.1
DB_USER="adsl"
DB_NAME="adsl"

# Tables name - this must be the same as /application/model/model.php
DROP_TABLE="DROPS"
PING_TABLE="PING"
SPEED_TABLE="SPEED"

TARGET1=8.8.8.8			# target ping Google DNS
TARGET2=208.67.222.222	# target ping OpenDNS
REFRESH=2 				# sleep time
PING_TOP=800			# TODO: read from /application/conf/conf.php
PING_OPT="-c1 -W3"		# Send 1 ping wait at least 3 seconds