#!/bin/bash
# Database conf info

# DB info
DBHOST=127.0.0.1
DBUSER="adsl"
DBNAME="adsl"

# Tables name
DROPTABLE="DISCONNECT"
PINGTABLE="PING"
SPEEDTABLE="SPEED"

TARGET1=8.8.8.8			# target ping
TARGET2=208.67.222.222	# target ping
REFRESH=2 				# sleep time